# @package _global_

conv_type: conv2d
downscale_type: maxpool2d
model:
  configuration:
    branch1:
      in_features: 1
      data: [f_depth, b_depth]
      out: 
        - [f_hm_markers, f_features]
        - [b_hm_markers, b_features]
    branch2:
      in_features: 309
      data: [f_features, b_features]
      out: 
        - [f_hm_joints, ""]
        - [b_hm_joints, ""]

  modules:
    branch1:
      modules:
        highres_standard_1:
          residual:
            type: bottleneck
            bottleneck_features: 128
            convolution: conv2d
            activation: relu
          fuse:
            convolution: conv2d
            activation:    
              intermediate: bn2d_relu
              prefusion: bn2d
              final: relu
            upscale: 
              type: upsample2d
              conv_up: true
        start_transition_standard_1:
          identity:
            convolution: conv2d
            kernel_size: 3
            stride: 1
            padding: 1
          branched:
            convolution: conv2d
            downscale: none
            kernel_size: 3
            stride: 2
            padding: 1
        stage_transition_standard_1:
          branched:
            convolution: conv2d
            downscale: none
            kernel_size: 3
            stride: 2
            padding: 1
        top_branch_1:
          convolution: conv2d
          activation: relu
          kernel_size: 1
          padding: 0
          inplace: false    
    branch2:
      modules:
        highres_standard_2:
          residual:
            type: bottleneck
            bottleneck_features: 128
            convolution: conv2d
            activation: relu
          fuse:
            convolution: conv2d
            activation:    
              intermediate: bn2d_relu
              prefusion: bn2d
              final: relu
            upscale: 
              type: upsample2d
              conv_up: true
        start_transition_standard_2:
          identity:
            convolution: conv2d
            kernel_size: 3
            stride: 1
            padding: 1
          branched:
            convolution: conv2d
            downscale: none
            kernel_size: 3
            stride: 2
            padding: 1
        stage_transition_standard_2:
          branched:
            convolution: conv2d
            downscale: none
            kernel_size: 3
            stride: 2
            padding: 1
        top_branch_2:
          convolution: conv2d
          activation: relu
          kernel_size: 1
          padding: 0
          inplace: false

  parameters:
    optimization:
      optimizers:
        adam:          
          lr: 3.0e-4
    schedule:
      schedulers:
        step:
          step_size: 4
          gamma: 0.95

  monads:
    grid:
      width: 40  # x
      height: 40 # y     
      inclusive: true
      order: xy
      mode: norm

    isotropic_gaussian:
      std: 3.0
      normalize: true
      scale: false
      grid_type: norm

    center_of_mass:
      flip: false
    
    concat:
      dim: 2

    transform:
      xyz_in_at: channel
      xyz_out_at: channel
      transpose: false

  feedforward:
    preprocess:
      grid:
        tensor: [f_depth]
        out: [grid]

      isotropic_gaussian:
        keypoints: [f_gt_markers_2d, b_gt_markers_2d, f_gt_joints_2d, b_gt_joints_2d]
        grid: [grid, grid, grid, grid]
        out: [f_hms_m_gt, b_hms_m_gt, f_hms_j_gt, b_hms_j_gt]

    postprocess:
      zmean:
        heatmaps: [f_hm_markers, b_hm_markers, f_hm_joints, b_hm_joints]
        out: [f_m_z_coords, b_m_z_coords, f_j_z_coords, b_j_z_coords]

      spatial_softmax:
        tensor: [f_hm_markers, b_hm_markers, f_hm_joints, b_hm_joints]
        out: [f_hm_markers, b_hm_markers, f_hm_joints, b_hm_joints]
      
      center_of_mass:
        grid: [grid, grid, grid, grid]
        heatmaps: [f_hm_markers, b_hm_markers, f_hm_joints, b_hm_joints]
        out: [f_pred_markers_2d, b_pred_markers_2d, f_pred_joints_2d, b_pred_joints_2d]

      concat:
        tensors:
          - [f_pred_markers_2d, f_m_z_coords]
          - [b_pred_markers_2d, b_m_z_coords]
          - [f_pred_joints_2d, f_j_z_coords]
          - [b_pred_joints_2d, b_j_z_coords]
        out: [f_pred_markers_3d, b_pred_markers_3d, f_pred_joints_3d, b_pred_joints_3d]

      fuse_coords:
        coords:
          - [f_pred_markers_3d, b_pred_markers_3d]
          - [f_pred_joints_3d, b_pred_joints_3d]
        out: [pred_markers_3d, pred_joints_3d]
        
      scale_coords:
        coords: [f_gt_markers_3d, f_gt_joints_3d, pred_markers_3d, pred_joints_3d]
        scales: [f_scale, f_scale, f_scale, f_scale]
        out: [f_gt_markers_3d_original, f_gt_joints_3d_original, pred_markers_3d_original, pred_joints_3d_original]