# @package _global_

experiment:
  visdom_ip: localhost
  name: democap_hrnet_2_views
  batch_size: 16
  workers: 4

engine:
  modules:
    import:
      run_path: false
      other_paths: ${project_path}
    manual_seed:
      seed: 1337
      deterministic: true

trainer:
  gpus: [1]
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  max_epochs: 200
  deterministic: false
  checkpoint:
    monitor: rmse_X_mae
    mode: min
    filename: '{epoch}_{rmse_X_mae:.2f}'

logging:
  name: ${experiment.name}
  loggers:
    visdom:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
    tabular:
      name: ${experiment.name}

visualization:
  batch_interval: 100
  visualizers:
    # feature2d:                      
    #   name: ${experiment.name}
    #   ip: ${experiment.visdom_ip}
    #   image: [b_hms_j_gt, b_hm_joints]
    #   type: [color, color]
    #   colormap: [turbo, turbo]
    #   transform: [minmax, minmax]

    image2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      image: [b_depth]
      type: [color]
      colormap: [turbo]
      transform: [minmax]

    pose2d:
      name: ${experiment.name}
      ip: ${experiment.visdom_ip}
      images: [f_depth]
      poses: [human_pose2d]
      gt: [f_gt_joints_2d]
      pred: [f_pred_joints_2d]
      pose_structure: 
        - [0, 1, 2, 3, 4]
        - [5, 6, 7]
        - [8, 9, 10]
        - [11, 12, 13, 14]
        - [15, 16, 17, 18]
      coords: [norm]
      color_gt: [cyan]
      color_pred: [red]
      reverse_coords: true
      rotate_image: false
      use_mask: false