# @package model.modules.branch1.modules.highres_standard_1

_target_: moai.modules.lightning.highres.HighResolution
residual:
  type: preactiv_bottleneck
  bottleneck_features: 128
  convolution: conv2d
  activation: relu
fuse:
  convolution: conv2d
  activation:    
    intermediate: relu_bn2d
    prefusion: bn2d
    final: relu
  upscale: 
    type: upsample2d
    conv_up: true