# @package model.modules.branch2.modules.hourglass_2

_target_: moai.modules.lightning.Hourglass
features: 309
depth: 1
convolution: conv2d
activation: relu_bn2d
# residual: preactiv_bottleneck
residual: bottleneck
downscale: maxpool2d_aa
upscale: upsample2d