# @package model.modules.branch2

_target_: src.modules.lightning.models.hrnet_mod.HRNetMod
configuration:
  stages: 4
  in_features: 309
  out_features: 19
  input: ???
  output: _joints_hms_pred
  # preproc:
  #   stem:
  #     blocks: [conv2d, conv2d]
  #     convolutions: [conv2d, conv2d]
  #     activations: [relu_bn2d, relu_bn2d]
  #     kernel_sizes: [3, 3]
  #     features: [32, 64]
  #     strides: [2, 2]
  #     paddings: [1, 1]
  residual: 
    block: bottleneck
    # block: preactiv_bottleneck
    convolution: conv2d
    activation: relu_bn2d
    features:
      in_features: [64, 309]
      out_features: [309, 309]
      bottleneck_features: [64, 64]
  branches:
    block: conv2d
    convolution: conv2d
    activation: relu
    kernel_size: 3
    stride: 1
    padding: 1
    start_features: 32
    modules: [1, 4, 3]
    depths: 
      - [4]
      - [4, 4, 4, 4]
      - [4, 4, 4]