# @package model.modules.branch2

_target_: moai.modules.lightning.models.StackedHourglassMod
configuration:
  stacks: 4
  in_features: 309
  out_features: 19
  output: _joints_hms_pred
  # preproc:
  #   block: identity
  #   convolution: identity
  #   activation: identity
  #   residual: identity
  #   downscale: identity
  #   stem:
  #     kernel_size: 7
  #     stride: 2
  #     padding: 3
  projection:
    block: conv2d
    convolution: conv2d
    activation: relu
  prediction:
    block: conv2d
    convolution: conv2d
    activation: relu
    dropout: 0.0
  merge:
    dropout: 0.0