# @package model.modules.branch2.modules.stage_transition_standard_2

_target_: moai.modules.lightning.highres.StageTransition
branched:
  convolution: conv2d
  activation: relu
  downscale: none # maxpool2d
  kernel_size: 3
  stride: 2
  padding: 1